# Generated by Django 4.0.3 on 2022-03-22 22:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('arenuo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('society_id', models.CharField(blank=True, max_length=10)),
                ('house_id', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='society',
            old_name='name',
            new_name='society_id',
        ),
        migrations.RemoveField(
            model_name='society',
            name='description',
        ),
        migrations.RemoveField(
            model_name='society',
            name='houses',
        ),
        migrations.RemoveField(
            model_name='society',
            name='members',
        ),
        migrations.AddField(
            model_name='society',
            name='house_ids',
            field=models.ManyToManyField(to='arenuo.house'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
