# Generated by Django 4.0.3 on 2022-03-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0002_data_date_data_soc_id_data_user_associated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='soc_id',
        ),
    ]
