# Generated by Django 4.0.3 on 2022-03-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenuo', '0002_customuser_rename_name_society_society_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
