# Generated by Django 4.0.3 on 2022-03-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenuo', '0003_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='b_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='b_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='b_3',
            field=models.FloatField(),
        ),
    ]
