# Generated by Django 4.0.3 on 2022-03-24 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0004_customuser_house_id_customuser_soc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(default=uuid.uuid4),
        ),
    ]
