# Generated by Django 4.0.3 on 2022-03-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenuo', '0004_alter_data_b_1_alter_data_b_2_alter_data_b_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='soc_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
