# Generated by Django 4.0.3 on 2022-03-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0006_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
