# Generated by Django 4.0.3 on 2022-03-24 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='soc_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aruneo.society'),
        ),
        migrations.AddField(
            model_name='data',
            name='user_associated',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
