# Generated by Django 4.0.3 on 2022-03-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0002_remove_customuser_id_remove_customuser_soc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='soc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aruneo.society'),
        ),
    ]
