# Generated by Django 4.0.3 on 2022-03-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0003_remove_customuser_house_id_remove_customuser_soc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='house_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='soc_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
