# Generated by Django 4.0.3 on 2022-03-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aruneo', '0005_alter_data_bucket_1_alter_data_bucket_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date',
            new_name='date_enter',
        ),
    ]
